language: node_js
node_js:
  - 12
script:
  - cd website; yarn install; yarn build
  - npx serve build/near-docs &
  - npx wait-on http://localhost:5000/
  - npx broken-link-checker -gro --exclude "localhost:3030" --exclude "https://github.com/nearprotocol/docs/tree/master/docs" --exclude "https://youtu.be" --exclude "http://near.ai/wbs" --exclude "https://www.youtube.com" --host-requests 2 http://localhost:5000 --exclude "https://rpc.testnet.near.org" --exclude "https://rpc.betanet.near.org" --exclude "https://rpc.near.org"  --exclude "https://crates.io/crates/near-sdk"  --exclude "https://github.com/nearprotocol/workshop"